INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (1, 1);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (3, 102);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (3, 103);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (4, 23);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (4, 24);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (4, 25);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (7, 16);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (7, 18);
INSERT INTO yu.sys_role_menu (role_id, menu_id) VALUES (7, 19);
